num1=float(input("Enter the 1st no:"))
num2=float(input("Enter the 1st no:"))
print("Addition=",num1+num2)
print("Subtraction=",num1-num2)
print("Multiplication=",num1*num2)
print("Division=",num1/num2)